### ISSUE TITLE
System fails to load `$` over HTTPS

### ISSUE THREAD

**Issue by andest01** [alexanderlarson/willsenpainoticeme#1]
currently, the site answers its fundamental question in a very very harsh manner. This is because jQuery failed to load, and this is because heroku moved over to HTTPS. Please load jQuery over https so i can have an immersive experience.

**Comment by alexanderlarson** [comment]
¯_(ツ)_/¯

**Comment by andest01** [comment]
ur a nice person and your hair smells pretty.
